services:
  # Start Docker Compose service
  - type: pserv
    runtime: docker
    name: backend-docker-compose
    rootDir: backend/endoscope
    buildCommand: docker-compose -f docker-compose.yml up -d
    disk:
      name: backend-docker-compose-disk
      mountPath: /app
      sizeGB: 10

  # Start Spring Boot application
  - type: web
    runtime: java
    name: spring-boot-app
    rootDir: backend/endoscope
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar backend/endoscope/endoscope-application/target/endoscope.jar
    disk:
      name: backend-spring-boot-disk
      mountPath: /app
      sizeGB: 10

  # Start React web application
  - type: web
    runtime: nodejs
    name: react-web-app
    rootDir: photo-gallery
    buildCommand: npm install && npm run build
    startCommand: npm start
    disk:
      name: react-web-disk
      mountPath: /app
      sizeGB: 10